CREATE TABLE MOVIE
(
MOVIE_ID INTEGER PRIMARY KEY,
NAME VARCHAR(300) NOT NULL,
YEAR INTEGER,
CRITIC_RATING NUMERIC(4,2) NOT NULL,
NUM_RATINGS INTEGER
);


CREATE TABLE GENRES
(
MOVIE_ID INTEGER NOT NULL, 
GENRE VARCHAR(100) NOT NULL,
PRIMARY KEY (MOVIE_ID, GENRE),
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID) ON DELETE CASCADE
);


CREATE TABLE TAG_MAP
(
TAG_ID INTEGER PRIMARY KEY,
TAG_NAME VARCHAR(200) NOT NULL
);

CREATE TABLE TAG_MOVIE_PAIR
(
MOVIE_ID INTEGER NOT NULL,
TAG_ID INTEGER NOT NULL,
WEIGHT INTEGER NOT NULL,
PRIMARY KEY(MOVIE_ID, TAG_ID),
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID) ON DELETE CASCADE,
FOREIGN KEY (TAG_ID) REFERENCES TAG_MAP(TAG_ID) ON DELETE CASCADE
);

CREATE TABLE ORIGIN_COUNTRY
(
MOVIE_ID INTEGER NOT NULL,
COUNTRY VARCHAR(100),
PRIMARY KEY (MOVIE_ID),
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID) ON DELETE CASCADE
);

CREATE TABLE FILM_COUNTRY
(
MOVIE_ID INTEGER NOT NULL,
COUNTRY VARCHAR(100) NOT NULL,
PRIMARY KEY (MOVIE_ID, COUNTRY),
FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE(MOVIE_ID) ON DELETE CASCADE
);

CREATE INDEX FILM_INDEX
ON FILM_COUNTRY(COUNTRY);

CREATE INDEX ORIGIN_INDEX
ON ORIGIN_COUNTRY(MOVIE_ID, COUNTRY);

CREATE INDEX TAG_MOVIE_PAIR_INDEX
ON TAG_MOVIE_PAIR(TAG_ID, WEIGHT);


CREATE INDEX GENRES_INDEX
ON GENRES(GENRE);

CREATE INDEX MOVIE_INDEX
ON MOVIE(MOVIE_ID, YEAR, CRITIC_RATING, NUM_RATINGS);


