DROP TABLE USER_TAGGED_TIMESTAMP;
DROP TABLE USER_TAGGED_MOVIES;
DROP TABLE USER_RATED_TIMESTAMP;
DROP TABLE USER_RATED_MOVIES;
DROP TABLE MOVIE_DIRECTORS;
DROP TABLE MOVIE_ACTORS;
DROP TABLE FILM_COUNTRY;
DROP TABLE ORIGIN_COUNTRY;
DROP TABLE TAG_MOVIE_PAIR;
DROP TABLE TAG_MAP;
DROP TABLE GENRES;
DROP TABLE MOVIE;





DROP INDEX MOVIE_INDEX;
DROP INDEX GENRES_INDEX;
DROP INDEX TAG_MOVIE_PAIR_INDEX;
DROP INDEX ORIGIN_INDEX;
DROP INDEX FILM_INDEX;