DROP TABLE FILM_COUNTRY;
DROP TABLE ORIGIN_COUNTRY;
DROP TABLE TAG_MOVIE_PAIR;
DROP TABLE TAG_MAP;
DROP TABLE GENRES;
DROP TABLE MOVIE;





DROP INDEX MOVIE_INDEX;
DROP INDEX GENRES_INDEX;
DROP INDEX TAG_MAP_INDEX;
DROP INDEX TAG_MOVIE_PAIR_INDEX;
DROP INDEX ORIGIN_INDEX;
DROP INDEX FILM_INDEX;